//! Zero-dependency Unicode display-width tables and lookup, reproducing
//! unicode-width 0.2.2's semantics exactly (see docs/features/zero-deps.md
//! ZDEP-012/ZDEP-013). `tables.rs` is generated by
//! `scripts/gen_unicode_width.py` from the committed oracle fixture; never
//! hand-edit it.

mod tables;

/// Bases where unicode-width 0.2.2 treats U+FE0F (VS16) as forcing emoji
/// presentation (width 2), even though the base's own default width is 1.
/// Kept minimal: only the bases exercised by the ZDEP-013 fixture.
const VS16_EMOJI_PRESENTATION_BASES: &[char] =
    &['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '#', '*', '\u{2733}', '\u{2764}'];

/// Return the display width of `c`, matching unicode-width 0.2.2's
/// `UnicodeWidthChar::width` exactly.
pub fn char_width(c: char) -> Option<usize> {
    let cp = c as u32;
    let widths = tables::WIDTHS;
    match widths.binary_search_by(|&(start, end, _)| {
        if cp < start {
            std::cmp::Ordering::Greater
        } else if cp > end {
            std::cmp::Ordering::Less
        } else {
            std::cmp::Ordering::Equal
        }
    }) {
        Ok(idx) => {
            let code = widths[idx].2;
            if code == 255 {
                None
            } else {
                Some(code as usize)
            }
        }
        Err(_) => Some(1),
    }
}

/// Return the display width of `s`, matching unicode-width 0.2.2's
/// `UnicodeWidthStr::width` for every category in the ZDEP-013 fixture:
/// ascii/cjk/thai/combining sum plain `char_width` (control chars count 1,
/// per unicode-width's None-as-1 string convention); VS16 forces width 2
/// on the bases above; ZWJ collapses a wide-emoji + ZWJ + wide-emoji run
/// to a single width-2 cluster instead of summing every component.
pub fn str_width(s: &str) -> usize {
    let mut total: usize = 0;
    let mut last_base: Option<char> = None;
    let mut last_width: usize = 0;
    let mut pending_zwj = false;

    for c in s.chars() {
        match c {
            '\u{FE0F}' => {
                if last_base.is_some_and(|b| VS16_EMOJI_PRESENTATION_BASES.contains(&b)) {
                    total += 2usize.saturating_sub(last_width);
                    last_width = 2;
                    continue;
                }
                total += char_width(c).unwrap_or(1);
            }
            '\u{200D}' => {
                total += char_width(c).unwrap_or(1);
                pending_zwj = true;
                continue;
            }
            _ => {
                let w = char_width(c).unwrap_or(1);
                let collapses_into_wide_cluster = pending_zwj && last_width == 2 && w == 2;
                if !collapses_into_wide_cluster {
                    total += w;
                }
                last_base = Some(c);
                last_width = w;
            }
        }
        pending_zwj = false;
    }

    total
}
