# Covers: ZDEP-012
# Requirement: generate(fixture_path) -> str reads the committed oracle
# fixture tests-rs/fixtures/unicode_width_0.2.2.txt (run-length rows
# <start-hex>..<end-hex>|<N|0|1|2|3>) and returns the full source text of
# crates/psmux-unicode/src/tables.rs, defining
# `pub(crate) const WIDTHS: &[(u32, u32, u8)]` sorted ascending by start,
# code 255 for None else the literal width 0/1/2/3. Width-1 rows are
# omitted since 1 is char_width's default for any point not covered by a
# row. Run as a script to regenerate the committed tables.rs from the
# committed fixture:
#   python scripts/gen_unicode_width.py

import os

HEADER = (
    "// Generated by scripts/gen_unicode_width.py from\n"
    "// tests-rs/fixtures/unicode_width_0.2.2.txt. Do not edit by hand.\n"
)


def generate(fixture_path):
    rows = []
    with open(fixture_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip("\n")
            if not line or line.startswith("#"):
                continue
            range_part, code = line.split("|")
            start_hex, end_hex = range_part.split("..")
            start = int(start_hex, 16)
            end = int(end_hex, 16)
            if code == "N":
                width_code = 255
            elif code == "1":
                continue  # 1 is char_width's default; omit from the table
            else:
                width_code = int(code)
            rows.append((start, end, width_code))

    lines = [HEADER.rstrip("\n"), "", "pub(crate) const WIDTHS: &[(u32, u32, u8)] = &["]
    for start, end, width_code in rows:
        lines.append(f"    (0x{start:04X}, 0x{end:04X}, {width_code}),")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    scripts_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(scripts_dir)
    fixture_path = os.path.join(repo_root, "tests-rs", "fixtures", "unicode_width_0.2.2.txt")
    out_path = os.path.join(repo_root, "crates", "psmux-unicode", "src", "tables.rs")
    content = generate(fixture_path)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"wrote {out_path} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
